from collections import OrderedDict
volumesObjects = OrderedDict([("ot",{
	"volume_id":1,
	"volume_title":"Old Testament",
}), ("nt",{
	"volume_id":2,
	"volume_title":"New Testament",
}), ("bm",{
	"volume_id":3,
	"volume_title":"Book of Mormon",
}), ("dc",{
	"volume_id":4,
	"volume_title":"Doctrine and Covenants",
}), ("pgp",{
	"volume_id":5,
	"volume_title":"Pearl of Great Price",
}) ])


volumesObjects["ot"]["books"] = OrderedDict([("gen",{
	"book_id" : 1,
	"book_title" : "Genesis",
	"num_chapters" : 50,
}), ("ex",{	"book_id" : 2,
	"book_title" : "Exodus",
	"num_chapters" : 40,
}), ("lev",{	"book_id" : 3,
	"book_title" : "Leviticus",
	"num_chapters" : 27,
}), ("num",{	"book_id" : 4,
	"book_title" : "Numbers",
	"num_chapters" : 36,
}), ("deut",{	"book_id" : 5,
	"book_title" : "Deuteronomy",
	"num_chapters" : 34,
}), ("josh",{	"book_id" : 6,
	"book_title" : "Joshua",
	"num_chapters" : 24,
}), ("judg",{	"book_id" : 7,
	"book_title" : "Judges",
	"num_chapters" : 21,
}), ("ruth",{	"book_id" : 8,
	"book_title" : "Ruth",
	"num_chapters" : 4,
}), ("1_sam",{	"book_id" : 9,
	"book_title" : "1 Samuel",
	"num_chapters" : 31,
}), ("2_sam",{	"book_id" : 10,
	"book_title" : "2 Samuel",
	"num_chapters" : 24,
}), ("1_kgs",{	"book_id" : 11,
	"book_title" : "1 Kings",
	"num_chapters" : 22,
}), ("2_kgs",{	"book_id" : 12,
	"book_title" : "2 Kings",
	"num_chapters" : 25,
}), ("1_chr",{	"book_id" : 13,
	"book_title" : "1 Chronicles",
	"num_chapters" : 29,
}), ("2_chr",{	"book_id" : 14,
	"book_title" : "2 Chronicles",
	"num_chapters" : 36,
}), ("ezra",{	"book_id" : 15,
	"book_title" : "Ezra",
	"num_chapters" : 10,
}), ("neh",{	"book_id" : 16,
	"book_title" : "Nehemiah",
	"num_chapters" : 13,
}), ("esth",{	"book_id" : 17,
	"book_title" : "Esther",
	"num_chapters" : 10,
}), ("job",{	"book_id" : 18,
	"book_title" : "Job",
	"num_chapters" : 42,
}), ("ps",{	"book_id" : 19,
	"book_title" : "Psalms",
	"num_chapters" : 150,
}), ("prov",{	"book_id" : 20,
	"book_title" : "Proverbs",
	"num_chapters" : 31,
}), ("eccl",{	"book_id" : 21,
	"book_title" : "Ecclesiastes",
	"num_chapters" : 12,
}), ("song",{	"book_id" : 22,
	"book_title" : "Solomon's Song",
	"num_chapters" : 8,
}), ("isa",{	"book_id" : 23,
	"book_title" : "Isaiah",
	"num_chapters" : 66,
	"lds_org" : "isa"
}), ("jer",{	"book_id" : 24,
	"book_title" : "Jeremiah",
	"num_chapters" : 52,
}), ("lam",{	"book_id" : 25,
	"book_title" : "Lamentations",
	"num_chapters" : 5,
	"lds_org" : "lam"
}), ("ezek",{	"book_id" : 26,
	"book_title" : "Ezekiel",
	"num_chapters" : 48,
}), ("dan",{	"book_id" : 27,
	"book_title" : "Daniel",
	"num_chapters" : 12,
}), ("hosea",{	"book_id" : 28,
	"book_title" : "Hosea",
	"num_chapters" : 14,
}), ("joel",{	"book_id" : 29,
	"book_title" : "Joel",
	"num_chapters" : 3,
}), ("amos",{	"book_id" : 30,
	"book_title" : "Amos",
	"num_chapters" : 9,
}), ("obad",{	"book_id" : 31,
	"book_title" : "Obadiah",
	"num_chapters" : 1,
}), ("jonah",{	"book_id" : 32,
	"book_title" : "Jonah",
	"num_chapters" : 4,
}), ("micah",{	"book_id" : 33,
	"book_title" : "Micah",
	"num_chapters" : 7,
}), ("nahum",{	"book_id" : 34,
	"book_title" : "Nahum",
	"num_chapters" : 3,
}), ("hab",{	"book_id" : 35,
	"book_title" : "Habakkuk",
	"num_chapters" : 3,
}), ("zeph",{	"book_id" : 36,
	"book_title" : "Zephaniah",
	"num_chapters" : 3,
}), ("hag",{	"book_id" : 37,
	"book_title" : "Haggai",
	"num_chapters" : 2,
}), ("zech",{	"book_id" : 38,
	"book_title" : "Zechariah",
	"num_chapters" : 14,
}), ("mal",{	"book_id" : 39,
	"book_title" : "Malachi",
	"num_chapters" : 4,
}) ])

volumesObjects["nt"]["books"] = OrderedDict([("matt",{	"book_id" : 40,
	"book_title" : "Matthew",
	"num_chapters" : 28,
	"lds_org" : "matt"
}), ("mark",{	"book_id" : 41,
	"book_title" : "Mark",
	"num_chapters" : 16,
}), ("luke",{	"book_id" : 42,
	"book_title" : "Luke",
	"num_chapters" : 24,
}), ("john",{	"book_id" : 43,
	"book_title" : "John",
	"num_chapters" : 21,
}), ("acts",{	"book_id" : 44,
	"book_title" : "Acts",
	"num_chapters" : 28,
}), ("rom",{	"book_id" : 45,
	"book_title" : "Romans",
	"num_chapters" : 16,
}), ("1_cor",{	"book_id" : 46,
	"book_title" : "1 Corinthians",
	"num_chapters" : 16,
}), ("2_cor",{	"book_id" : 47,
	"book_title" : "2 Corinthians",
	"num_chapters" : 13,
}), ("gal",{	"book_id" : 48,
	"book_title" : "Galatians",
	"num_chapters" : 6,
}), ("eph",{	"book_id" : 49,
	"book_title" : "Ephesians",
	"num_chapters" : 6,
}), ("philip",{	"book_id" : 50,
	"book_title" : "Philippians",
	"num_chapters" : 4,
}), ("col",{	"book_id" : 51,
	"book_title" : "Colossians",
	"num_chapters" : 4,
}), ("1_thes",{	"book_id" : 52,
	"book_title" : "1 Thessalonians",
	"num_chapters" : 5,
	"lds_org" : "1_thes"
}), ("2_thes",{	"book_id" : 53,
	"book_title" : "2 Thessalonians",
	"num_chapters" : 3,
}), ("1_tim",{	"book_id" : 54,
	"book_title" : "1 Timothy",
	"num_chapters" : 6,
}), ("2_tim",{	"book_id" : 55,
	"book_title" : "2 Timothy",
	"num_chapters" : 4,
}), ("titus",{	"book_id" : 56,
	"book_title" : "Titus",
	"num_chapters" : 3,
}), ("philem",{	"book_id" : 57,
	"book_title" : "Philemon",
	"num_chapters" : 1,
}), ("heb",{	"book_id" : 58,
	"book_title" : "Hebrews",
	"num_chapters" : 13,
}), ("james",{	"book_id" : 59,
	"book_title" : "James",
	"num_chapters" : 5,
	"lds_org" : "james"
}), ("1_pet",{	"book_id" : 60,
	"book_title" : "1 Peter",
	"num_chapters" : 5,
}), ("2_pet",{	"book_id" : 61,
	"book_title" : "2 Peter",
	"num_chapters" : 3,
	"lds_org" : "2_pet"
}), ("1_jn",{	"book_id" : 62,
	"book_title" : "1 John",
	"num_chapters" : 5,
	"lds_org" : "1_jn"
}), ("2_jn",{	"book_id" : 63,
	"book_title" : "2 John",
	"num_chapters" : 1,
}), ("3_jn",{	"book_id" : 64,
	"book_title" : "3 John",
	"num_chapters" : 1,
}), ("jude",{	"book_id" : 65,
	"book_title" : "Jude",
	"num_chapters" : 1,
}), ("rev",{	"book_id" : 66,
	"book_title" : "Revelation",
	"num_chapters" : 22,
}) ])

volumesObjects["bm"]["books"] = OrderedDict([("1_ne",{	"book_id" : 67,
	"book_title" : "1 Nephi",
	"num_chapters" : 22,
}), ("2_ne",{	"book_id" : 68,
	"book_title" : "2 Nephi",
	"num_chapters" : 33,
}), ("jacob",{	"book_id" : 69,
	"book_title" : "Jacob",
	"num_chapters" : 7,
}), ("enos",{	"book_id" : 70,
	"book_title" : "Enos",
	"num_chapters" : 1,
}), ("jarom",{	"book_id" : 71,
	"book_title" : "Jarom",
	"num_chapters" : 1,
}), ("omni",{	"book_id" : 72,
	"book_title" : "Omni",
	"num_chapters" : 1,
}), ("w_of_m",{	"book_id" : 73,
	"book_title" : "Words of Mormon",
	"num_chapters" : 1,
}), ("mosiah",{	"book_id" : 74,
	"book_title" : "Mosiah",
	"num_chapters" : 29,
}), ("alma",{	"book_id" : 75,
	"book_title" : "Alma",
	"num_chapters" : 63,
}), ("hel",{	"book_id" : 76,
	"book_title" : "Helaman",
	"num_chapters" : 16,
}), ("3_ne",{	"book_id" : 77,
	"book_title" : "3 Nephi",
	"num_chapters" : 30,
}), ("4_ne",{	"book_id" : 78,
	"book_title" : "4 Nephi",
	"num_chapters" : 1,
}), ("morm",{	"book_id" : 79,
	"book_title" : "Mormon",
	"num_chapters" : 9,
}), ("ether",{	"book_id" : 80,
	"book_title" : "Ether",
	"num_chapters" : 15,
}), ("moro",{	"book_id" : 81,
	"book_title" : "Moroni",
	"num_chapters" : 10,
}) ])

volumesObjects["dc"]["books"] = OrderedDict([("dc",{	"book_id" : 82,
	"book_title" : "Doctrine and Covenants",
	"num_chapters" : 138,
}) ])

volumesObjects["pgp"]["books"] =  OrderedDict([("moses",{	"book_id" : 83,
	"book_title" : "Moses",
	"num_chapters" : 8,
}), ("abr",{	"book_id" : 84,
	"book_title" : "Abraham",
	"num_chapters" : 5,
}), ("js_m",{	"book_id" : 85,
	"book_title" : "Joseph Smith--Matthew",
	"num_chapters" : 1,
}), ("js_h",{	"book_id" : 86,
	"book_title" : "Joseph Smith--History",
	"num_chapters" : 1,
}), ("a_of_f",{	"book_id" : 87,
	"book_title" : "Articles of Faith",
	"num_chapters" : 1,
	"lds_org" : "a_of_f"
}) ])